### ISSUE TITLE
Map.build panicking at runtime 'attempt to create unaligned or null slice'

### ISSUE THREAD

**Issue by ekaats** [StarArawn/bevy_ecs_tilemap#9]
I've just started learning rust, so sorry in advance if my explanation is not too helpful. I am running into an issue when adopting or running your examples.

`
 cargo run --release --example iso
    Finished release [optimized] target(s) in 0.37s
     Running "/tmp/bevy_ecs_tilemap/target/release/examples/iso"

[2021-05-02T14:50:04Z WARN  gfx_backend_vulkan] Skipping memory type with unknown flags DEVICE_LOCAL | DEVICE_COHERENT_AMD | DEVICE_UNCACHED_AMD
[2021-05-02T14:50:04Z WARN  gfx_backend_vulkan] Skipping memory type with unknown flags HOST_VISIBLE | HOST_COHERENT | DEVICE_COHERENT_AMD | DEVICE_UNCACHED_AMD
[2021-05-02T14:50:04Z WARN  gfx_backend_vulkan] Skipping memory type with unknown flags DEVICE_LOCAL | HOST_VISIBLE | HOST_COHERENT | DEVICE_COHERENT_AMD | DEVICE_UNCACHED_AMD
[2021-05-02T14:50:04Z WARN  gfx_backend_vulkan] Skipping memory type with unknown flags HOST_VISIBLE | HOST_COHERENT | HOST_CACHED | DEVICE_COHERENT_AMD | DEVICE_UNCACHED_AMD
[2021-05-02T14:50:04Z INFO  winit::platform_impl::platform::x11::window] Guessed window scale factor: 1
[2021-05-02T14:50:04Z INFO  bevy_ecs_tilemap::chunk] Re-meshing chunk at: MapVec2 { x: 0, y: 0 } layer id of: 0
[2021-05-02T14:50:04Z INFO  bevy_ecs_tilemap::chunk] Re-meshing chunk at: MapVec2 { x: 0, y: 1 } layer id of: 0
[2021-05-02T14:50:04Z INFO  bevy_ecs_tilemap::chunk] Re-meshing chunk at: MapVec2 { x: 1, y: 0 } layer id of: 0
[2021-05-02T14:50:04Z INFO  bevy_ecs_tilemap::chunk] Re-meshing chunk at: MapVec2 { x: 1, y: 1 } layer id of: 0
[2021-05-02T14:50:04Z INFO  bevy_ecs_tilemap::chunk] Re-meshing chunk at: MapVec2 { x: 1, y: 1 } layer id of: 1
[2021-05-02T14:50:04Z INFO  bevy_ecs_tilemap::chunk] Re-meshing chunk at: MapVec2 { x: 1, y: 0 } layer id of: 1
[2021-05-02T14:50:04Z INFO  bevy_ecs_tilemap::chunk] Re-meshing chunk at: MapVec2 { x: 0, y: 0 } layer id of: 1
[2021-05-02T14:50:04Z INFO  bevy_ecs_tilemap::chunk] Re-meshing chunk at: MapVec2 { x: 0, y: 1 } layer id of: 1
[2021-05-02T14:50:04Z INFO  bevy_ecs_tilemap::chunk] Re-meshing chunk at: MapVec2 { x: 1, y: 0 } layer id of: 2
[2021-05-02T14:50:04Z INFO  bevy_ecs_tilemap::chunk] Re-meshing chunk at: MapVec2 { x: 0, y: 1 } layer id of: 2
[2021-05-02T14:50:04Z INFO  bevy_ecs_tilemap::chunk] Re-meshing chunk at: MapVec2 { x: 0, y: 0 } layer id of: 2
[2021-05-02T14:50:04Z INFO  bevy_ecs_tilemap::chunk] Re-meshing chunk at: MapVec2 { x: 1, y: 1 } layer id of: 2
thread 'main' panicked at 'attempt to create unaligned or null slice', /usr/lib/rust/1.51.0/lib/rustlib/src/rust/library/core/src/slice/raw.rs:90:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Segmentation fault
`

This happens with Rust 1.51.0 (no nightly) and line `map.build(&mut commands, &mut meshes, material_handle.clone(), map_entity, true);` seems to be the offending line.

That is as far as my Rust debugging skills go at the moment though. Any idea what might be the issue here?

**Comment by StarArawn** [comment]
Can you run this with:
`RUST_BACKTRACE=1`?

Also what does your `Map::new` look like?

**Comment by ekaats** [comment]
Thank you for your work and your quick reply!

This is the stack backtrace of the unmodified iso.rs example:

stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.51.0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/1.51.0/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/1.51.0/library/core/src/panicking.rs:50:5
   3: spirv_reflect::convert::ffi_to_block_variable
   4: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   5: spirv_reflect::convert::ffi_to_block_variable
   6: spirv_reflect::convert::ffi_to_descriptor_binding
   7: spirv_reflect::convert::ffi_to_descriptor_set
   8: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   9: spirv_reflect::ShaderModule::enumerate_descriptor_sets
  10: bevy_render::shader::shader_reflect::<impl bevy_render::shader::ShaderLayout>::from_spirv
  11: bevy_render::shader::shader::Shader::reflect_layout
  12: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
  13: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  14: bevy_render::renderer::render_resource_context::RenderResourceContext::reflect_pipeline_layout
  15: bevy_render::pipeline::pipeline_compiler::PipelineCompiler::compile_pipeline
  16: bevy_render::draw::DrawContext::set_pipeline
  17: bevy_render::pipeline::render_pipelines::draw_render_pipelines_system
  18: <bevy_ecs::system::into_system::FunctionSystem<In,Out,Param,Marker,F> as bevy_ecs::system::system::System>::run_unsafe
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  20: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  21: async_task::raw::RawTask<F,T,S>::run
  22: async_executor::Executor::try_tick
  23: std::thread::local::LocalKey<T>::with
  24: <bevy_ecs::schedule::executor_parallel::ParallelExecutor as bevy_ecs::schedule::executor::ParallelSystemExecutor>::run_systems
  25: <bevy_ecs::schedule::stage::SystemStage as bevy_ecs::schedule::stage::Stage>::run
  26: bevy_ecs::schedule::Schedule::run_once
  27: bevy_winit::winit_runner_with::{{closure}}
  28: winit::platform_impl::platform::x11::EventLoop<T>::run_return
  29: winit::platform_impl::platform::x11::EventLoop<T>::run
  30: winit::platform_impl::platform::EventLoop<T>::run
  31: winit::event_loop::EventLoop<T>::run
  32: bevy_winit::run
  33: bevy_winit::winit_runner_with
  34: core::ops::function::Fn::call
  35: bevy_app::app_builder::AppBuilder::run
  36: iso::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Segmentation fault


I didn't modify the code of the example, so the lines look like this:

19:    let mut map = Map::new(Vec2::new(2.0, 2.0).into(), Vec2::new(8.0, 8.0).into(), Vec2::new(64.0, 64.0), Vec2::new(640.0, 1024.0), 0);
31:        let mut map = Map::new(Vec2::new(2.0, 2.0).into(), Vec2::new(8.0, 8.0).into(), Vec2::new(64.0, 64.0), Vec2::new(640.0, 1024.0), z + 1);

I've been tinkering with the code as well, and if I comment out the map.build(); line it runs fine (but obviously not much exciting happens).

**Comment by StarArawn** [comment]
Can you run the bevy sprite example? The backtrace indicates that the pipeline reflection is failing which is a little odd and makes me think the spir-v code generated for the shader is somehow different on your machine.. 🤔

**Comment by ekaats** [comment]
You are right, the Bevy sprite example gives the same error, so apparently the issue is on my end. Thank you for looking into it though. I'll close the issue for now and update if applicable.

**Comment by StarArawn** [comment]
Thank you! Hope you can get this resolved!
